require("rbonsembiante.plugins-setup")
require("rbonsembiante.core.options")
require("rbonsembiante.core.keymaps")
require("rbonsembiante.core.colorscheme")
require("rbonsembiante.plugins.nvim-tree")
require("rbonsembiante.plugins.comment")
require("rbonsembiante.plugins.lualine")
require("rbonsembiante.plugins.telescope")
require("rbonsembiante.plugins.nvim-cmp")
require("rbonsembiante.plugins.lsp.mason")
require("rbonsembiante.plugins.lsp.lspsaga")
require("rbonsembiante.plugins.lsp.lspconfig")
vim.lsp.set_log_level("off")

